#!/bin/bash

echo "version = $1"

# Get version number from version tag
JAR_VERSION=`echo $1 | cut -d'v' -f2`
echo "jar = $JAR_VERSION"
# Set new library version in pom.xml using mvn versions:set command
# These new pom.xml and changelog.md generated by @semantic-release/changelog
# will be commit it by @semantic-release/git

# Package the new library version and copy it to release folder
# These files will be upload to github by @semantic-release/github
chmod +x gradlew
./gradlew build
mkdir release && cp build/libs/*.jar release

printenv